const en = {
  pageTitle: 'FORK YOU — Fork the future.',
  pageDescription:
    'They want to eat everything. Fork the future. Find open-source projects, companies, and public-interest organizations worth your skills.',
  skip: 'Skip to directory',
  home: 'FORK YOU home',
  navigation: 'Main navigation',
  news: 'News',
  manifesto: 'Why we’re here',
  directory: 'Find your people',
  contribute: 'Help build the list',
  kicker: 'THE FUTURE IS STILL UP FOR GRABS',
  headline: 'They want to eat everything.',
  headlineAccent: 'Fork the future.',
  intro:
    'An open future needs people to build it. Find an open-source project, a company building in the open, or a public-interest organization worth your skills.',
  places: (n: number) => `${n} places to start`,
  concernTitle: 'What are we worried about?',
  concern:
    'Assume frontier AI labs will try to eat everything: the tools we use, the work we do, and the attention we have left. What happens when a handful of companies becomes the way into everything else?',
  possibility:
    'That is our starting assumption. The future is still something people can shape. We want tools we can inspect, communities that have a say, and work we can take with us when we leave.',
  motto: 'Open code. Shared power. Actual people.',
  forkTitle: 'Why “FORK YOU”?',
  fork: 'In software, a fork takes shared code in a new direction. This is an invitation to do the same with the future. Write code. Design something useful. Translate a guide. Defend someone’s rights. Help keep an alternative alive.',
  participateTitle: 'What can I do?',
  projectAction: 'Contribute to an open project.',
  projectHelp: 'Code, documentation, design, translation, and more.',
  careerAction: 'Find paid work you want to stand behind.',
  careerHelp: 'Explore companies, co-ops, and nonprofits.',
  volunteerAction: 'Give your time to the public interest.',
  volunteerHelp: 'Help a community or a cause that matters to you.',
  directoryTitle: 'Find your people.',
  curated: 'Curated, with sources.',
  search: 'Search organizations, causes, or skills',
  searchPlaceholder: 'Search a cause, skill, or name…',
  clearSearch: 'Clear search',
  involvement: 'How you want to get involved',
  organizationType: 'Organization type',
  matches: (n: number) => `${n} ${n === 1 ? 'match' : 'matches'}`,
  emptyTitle: 'No people found. Yet.',
  emptyHelp: 'Try a broader search or a different way to get involved.',
  clearFilters: 'Clear all filters',
  directoryNote:
    'Careers links lead to official careers pages. They do not mean an organization is hiring today. Contribution and volunteer routes may be unpaid.',
  communityTitle: 'The list needs your people.',
  community:
    'Know a project we missed? Spotted something out of date? Help make this directory more useful, with sources to back it up.',
  suggest: 'Suggest a project',
  correction: 'Report a correction',
  submission:
    'Opens a public GitHub form. A GitHub account is required. We review suggestions and corrections before updating the list.',
  standardsTitle: 'Who gets on the list?',
  reasonTitle: 'A reason to be here',
  reason:
    'Open-source work, shared ownership, or a documented public-interest mission. We explain the connection.',
  routeTitle: 'A real way in',
  route:
    'An official contribution guide, careers page, or volunteer route. Paid work and unpaid participation stay clearly labeled.',
  evidenceTitle: 'Receipts, not righteousness',
  evidence:
    'Sources and review dates. No invented jobs, independence scores, or claims that an organization is “AI-proof.”',
  openTitle: 'Does “open” mean perfect?',
  open: 'No. Open source can pay the bills. Nonprofits can make bad decisions. Read the governance notes and sources, ask questions, and decide for yourself. A listing does not mean an organization endorses FORK YOU.',
  slogan: 'The future isn’t takeout.',
  forkSite: 'Fork this site',
  back: 'Back to the directory',
  categories: {
    all: 'Everyone',
    project: 'Open projects',
    company: 'Companies & co-ops',
    nonprofit: 'NGOs & nonprofits',
  },
  singular: {
    project: 'Open project',
    company: 'Company / co-op',
    nonprofit: 'NGO / nonprofit',
  },
  intents: {
    all: 'Any way in',
    contribute: 'Contribute to a project',
    careers: 'Explore paid work',
    volunteer: 'Volunteer my time',
  },
  whyListed: (name: string) => `Why ${name} is listed`,
  whyButton: 'Why them?',
  receipts: 'THE RECEIPTS',
  whyPicked: 'Why we picked them',
  editorial: 'Our editorial assessment',
  governance: 'How it is organized',
  wayIn: 'Your way in',
  sources: 'Read the sources',
  reviewed: (date: string) =>
    `Sources reviewed ${date}. Opportunities can change.`,
  detailNote:
    'A listing is a place to investigate, not a certification of an employer or an endorsement of our manifesto by this organization.',
  correctionFor: (name: string) => `Report a correction for ${name} on GitHub`,
  publicForm: 'Public GitHub form. Sign-in required.',
  close: 'Close',
  newsKicker: 'NEWS / POWER / ACCOUNTABILITY',
  newsTitle: 'News, with receipts.',
  newsIntro:
    'Frontier AI, money, and who gets a say. Read what happened, what’s disputed, and why we’re paying attention.',
  readContext: 'Read the context',
  contextFor: (title: string) => `Read the context: ${title}`,
  sourceCount: (n: number) => `${n} sources`,
  sourceLabel: (n: number, label: string) => `Source ${n}: ${label}`,
  editorialView: 'Our editorial view',
  ourTake: 'Our take · Opinion',
  sourceKinds: {
    'Primary source': 'Primary source',
    Reporting: 'Reporting',
    Opinion: 'Opinion',
  },
  checked: 'Sources checked',
  datedBrief:
    '(UTC). This is a dated brief; later developments may change the picture.',
  newsCorrection: (title: string) => `Report a correction: ${title}`,
  bringStory: 'Bring a story. Bring sources.',
  newsSubmission:
    'Suggestions and corrections open public GitHub forms and require sign-in. We review sources before publishing or updating a brief.',
};

const zh: typeof en = {
  pageTitle: 'FORK YOU — 未来，我们另开一条路。',
  pageDescription:
    '他们想把一切都吃下。未来，我们另开一条路。一起找找值得参与的开源项目、开放协作的公司和公益组织。',
  skip: '跳到项目目录',
  home: 'FORK YOU 首页',
  navigation: '网站导航',
  news: '看看新闻',
  manifesto: '为什么做这个',
  directory: '找到同路人',
  contribute: '一起补充名单',
  kicker: '未来还没定，咱们也有份',
  headline: '他们想把一切都吃下。',
  headlineAccent: '未来，我们另开一条路。',
  intro:
    '想要一个开放的未来，总得有人动手。这里有开源项目、开放协作的公司，还有值得你出一份力的公益组织。看看有没有你想加入的。',
  places: (n) => `${n} 个地方，总有一个能开始`,
  concernTitle: '我们在担心什么？',
  concern:
    '不妨先做个假设：那些走在 AI 最前面的公司，会想把什么都吃下——我们用的工具、做的工作，连剩下那点注意力也不放过。如果做什么都得经过这几家公司，会怎样？',
  possibility:
    '这是我们思考的起点。未来还没定，我们仍然能参与。我们想要看得懂、改得了的工具，能一起商量事情的社区，还有离开一个平台也带得走的成果。',
  motto: '代码能打开，事情一起定，人得算数。',
  forkTitle: '为什么叫「FORK YOU」？',
  fork: '写代码时，fork 就是拿一份共享的代码，走出另一条路。我们也想邀你这样对待未来：写点代码，做个有用的设计，翻译一份指南，帮人守住权利。让大家多一种选择。',
  participateTitle: '我能做点什么？',
  projectAction: '给开源项目搭把手。',
  projectHelp: '写代码、补文档、做设计、帮忙翻译，都算。',
  careerAction: '找一份自己愿意支持的工作。',
  careerHelp: '看看这些公司、合作社和非营利组织。',
  volunteerAction: '为在意的事出一份力。',
  volunteerHelp: '给社区帮个忙，或者支持你关心的公益方向。',
  directoryTitle: '找到你的同路人。',
  curated: '有筛选，也有出处。',
  search: '搜索组织、关注的话题或技能',
  searchPlaceholder: '搜名字、技能，或你关心的事…',
  clearSearch: '清空搜索',
  involvement: '你想怎么参与',
  organizationType: '组织类型',
  matches: (n) => `找到 ${n} 个`,
  emptyTitle: '暂时没找到合适的。',
  emptyHelp: '换个关键词，或者试试别的参与方式。',
  clearFilters: '清空筛选，重新看看',
  directoryNote:
    '招聘链接通往各家的官方页面，不代表他们今天一定在招人。参与项目或做志愿者，也可能没有报酬。',
  communityTitle: '把你认识的好项目也带来。',
  community:
    '有我们漏掉的项目？还是发现哪条信息过时了？欢迎帮忙补充，记得带上出处，让这份名单更有用。',
  suggest: '推荐一个项目',
  correction: '告诉我们哪里不对',
  submission:
    '会打开公开的 GitHub 表单，需要登录 GitHub。我们核对建议和更正后，再更新名单。',
  standardsTitle: '什么样的组织会被列进来？',
  reasonTitle: '有值得了解的理由',
  reason:
    '做开源、共同拥有，或有据可查地服务公共利益。我们会说清楚为什么选它。',
  routeTitle: '真的能参与进去',
  route:
    '有官方贡献指南、招聘页或志愿者入口。有报酬和无报酬的参与方式，会分别写清楚。',
  evidenceTitle: '看出处，别看光环',
  evidence:
    '附上来源和核对日期。不编招聘信息，不打「独立性分数」，也不保证谁能躲过 AI 的冲击。',
  openTitle: '开放，就一定好吗？',
  open: '当然不是。做开源也要养活自己，非营利组织也会做错决定。看看它怎么运作，读读来源，多问几句，再自己判断。被列在这里，也不代表对方支持 FORK YOU。',
  slogan: '未来，不能让几家公司打包带走。',
  forkSite: 'Fork 这个网站',
  back: '回到项目目录',
  categories: {
    all: '全部',
    project: '开源项目',
    company: '公司与合作社',
    nonprofit: '公益与非营利组织',
  },
  singular: {
    project: '开源项目',
    company: '公司 / 合作社',
    nonprofit: '公益 / 非营利组织',
  },
  intents: {
    all: '先都看看',
    contribute: '参与开源项目',
    careers: '找有报酬的工作',
    volunteer: '做志愿者',
  },
  whyListed: (name) => `为什么把 ${name} 列在这里`,
  whyButton: '为什么选它？',
  receipts: '理由和出处都在这儿',
  whyPicked: '我们为什么选它',
  editorial: '这是我们的判断',
  governance: '它是怎么运作的',
  wayIn: '你可以怎么参与',
  sources: '看看原始出处',
  reviewed: (date) => `上次核对这些来源是在 ${date}，具体机会可能会变。`,
  detailNote:
    '这份名单给你一个了解的起点，不是雇主认证，也不代表这个组织赞同我们的主张。',
  correctionFor: (name) => `到 GitHub 更正 ${name} 的信息`,
  publicForm: '这是公开的 GitHub 表单，需要登录。',
  close: '关闭',
  newsKicker: '新闻 / 权力 / 谁来负责',
  newsTitle: '聊新闻，也摆出处。',
  newsIntro:
    'AI 大公司、钱，还有谁说了算。发生了什么，哪里还有争议，我们为什么在意，都放在这里。',
  readContext: '展开看看来龙去脉',
  contextFor: (title) => `展开看看：${title}`,
  sourceCount: (n) => `${n} 个来源`,
  sourceLabel: (n, label) => `来源 ${n}：${label}`,
  editorialView: '我们的看法',
  ourTake: '我们怎么看 · 观点',
  sourceKinds: {
    'Primary source': '一手来源',
    Reporting: '新闻报道',
    Opinion: '观点文章',
  },
  checked: '上次核对来源：',
  datedBrief: '（UTC）。这里记录的是当时的信息，后续进展可能改变判断。',
  newsCorrection: (title) => `更正这篇内容：${title}`,
  bringStory: '有值得聊的新闻？带着出处来。',
  newsSubmission:
    '推荐新闻或提出更正，会打开公开的 GitHub 表单，需要登录。我们核对来源后，再发布或更新。',
};

export const copy = { en, 'zh-CN': zh };
